services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://fauxpg:kelapasawit1@db/sapdb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: fauxpg
      POSTGRES_PASSWORD: kelapasawit1
      POSTGRES_DB: sapdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d   # mount init.sql and other scripts
   
  migrate:
    image: postgres:15
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    entrypoint: ["sh", "-c", "for f in /migrations/*.sql; do psql -h db -U fauxpg -d sapdb -f $f; done"]
    environment:
      PGPASSWORD: kelapasawit1

volumes:
  postgres_data:

