services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://fauxpg:kelapasawit1@db/sapdb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: fauxpg
      POSTGRES_PASSWORD: kelapasawit1
      POSTGRES_DB: sapdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d   # mount init.sql and other scripts

volumes:
  postgres_data:

